export const BOOKS = [
  {
    id: "bk-atomic-habits",
    title: "Atomic Habits",
    author: "James Clear",
    price: 14.99,
    rating: 4.8,
    year: 2018,
    category: "Self-Help",
    tags: ["habits", "productivity", "behavior"],
    description:
      "An easy and proven way to build good habits and break bad ones. Practical techniques to make small changes that deliver remarkable results.",
  },
  {
    id: "bk-deep-work",
    title: "Deep Work",
    author: "Cal Newport",
    price: 13.49,
    rating: 4.7,
    year: 2016,
    category: "Productivity",
    tags: ["focus", "work", "attention"],
    description:
      "Rules for focused success in a distracted world. Learn how to cultivate deep work and dramatically improve your output.",
  },
  {
    id: "bk-clean-code",
    title: "Clean Code",
    author: "Robert C. Martin",
    price: 31.99,
    rating: 4.9,
    year: 2008,
    category: "Programming",
    tags: ["software", "best practices", "craft"],
    description:
      "A handbook of agile software craftsmanship. Practical advice for writing readable, maintainable, and quality code.",
  },
  {
    id: "bk-pragmatic-programmer",
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt, David Thomas",
    price: 28.5,
    rating: 4.8,
    year: 1999,
    category: "Programming",
    tags: ["software", "career", "craft"],
    description:
      "Classic lessons for pragmatic thinking and effective software development."
  },
  {
    id: "bk-algorithms",
    title: "Introduction to Algorithms",
    author: "Thomas H. Cormen et al.",
    price: 69.95,
    rating: 4.6,
    year: 2009,
    category: "Computer Science",
    tags: ["algorithms", "data structures"],
    description:
      "Comprehensive textbook on algorithms covering theory and practice.",
  },
  {
    id: "bk-sapiens",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    price: 16.75,
    rating: 4.7,
    year: 2015,
    category: "History",
    tags: ["evolution", "culture", "society"],
    description:
      "Explores the history and impact of Homo sapiens on Earth.",
  },
  {
    id: "bk-education",
    title: "Educated",
    author: "Tara Westover",
    price: 12.99,
    rating: 4.7,
    year: 2018,
    category: "Memoir",
    tags: ["resilience", "family", "education"],
    description:
      "A memoir about a woman who, kept out of school, leaves her survivalist family and goes on to earn a PhD.",
  },
  {
    id: "bk-hp1",
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    price: 9.99,
    rating: 4.8,
    year: 1997,
    category: "Fantasy",
    tags: ["magic", "adventure", "friendship"],
    description:
      "The first book in the beloved Harry Potter series.",
  },
  {
    id: "bk-got",
    title: "A Game of Thrones",
    author: "George R.R. Martin",
    price: 11.5,
    rating: 4.6,
    year: 1996,
    category: "Fantasy",
    tags: ["dragons", "politics", "epic"],
    description:
      "The first book in A Song of Ice and Fire series.",
  },
  {
    id: "bk-think-fast-slow",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    price: 14.25,
    rating: 4.6,
    year: 2011,
    category: "Psychology",
    tags: ["biases", "decision-making"],
    description:
      "A tour of the mind and the two systems that drive the way we think.",
  },
  {
    id: "bk-art-of-war",
    title: "The Art of War",
    author: "Sun Tzu",
    price: 6.99,
    rating: 4.4,
    year: -500,
    category: "Philosophy",
    tags: ["strategy", "leadership"],
    description:
      "Ancient treatise on military strategy and tactics with modern applications.",
  },
];
